Rails.application.routes.draw do

	get '/' => 'home#top'

	devise_for :users
		## devise_routes
		# get    '/users/sign_in' => 'devise/session#new'
		# post   '/users/sign_in' => 'devise/session#create'
		# delete '/users/sign_out' => 'devise/session#desetroy'
		# get    '/users/password/new' => 'devise/passwords#new'
		# get    '/users/password/edit' => 'devise/passwords#edit'
		# patch  '/users/password' => 'devise/passwords#update'
		# put    '/users/password' => 'devise/passwords#update'
		# post   '/users/password' => 'devise/passwords#create'
		# get    '/users/cancel' => 'devise/registrations#cancel'
		# get    '/users/sign_up' => 'devise/registrations#new'
		# get    '/users/edit' => 'devise/registrations#edit'
		# PATCH  '/users' => 'devise/registrations#update'
		# PUT    '/users' => 'devise/registrations#update'
		# DELETE '/users' => 'devise/registrations#destroy'
		# POST   '/users' => 'devise/registrations#create'

  get    '/users/:id' => 'users#show'
  get    '/users/:id/edit' => 'users#edit'
  patch  '/users/:id' => 'users#update'
  get    '/tasks' => 'tasks#new'
  post   '/tasks' => 'tasks#create'
  get    '/tasks/:id/edit' => 'tasks#edit'
  patch  '/tasks/:id' => 'tasks#update'
  delete '/tasks/:id' => 'tasks#destroy'
  post   '/task_lists' => 'tasks#create'
  delete '/task_lists' => 'tasks#destroy'
  patch  '/task_lists' => 'tasks#update'
  get    '/tags' => 'tags#new'
  post   '/tags' => 'tags#create'
  delete '/tags/:id' => 'tags#destroy'
  post   '/tag_lists' => 'tag_lists#create'
  delete '/tag_lists/:id' => 'tag_lists#destroy'
  patch  '/tags_lists/:id' => 'tag_lists#update'
	get    '/schedule_items' => 'schedule_items#index'
  post   '/schedule_items' => 'schedule_items#create'
  delete '/schedule_items/:id' => 'schedule_items#destroy'
  patch  '/schedule_itmes/:id' => 'schedule_items#update'
  post   '/list_items' => 'list_items#create'
  delete '/list_items/:id' => 'list_items#destroy'
  patch  '/list_items/:id' => 'list_itmes#update'
  post   '/history_items' => 'history_items#create'
  get    '/history_items' => 'history_items#index'
  delete '/history_items/:id' => 'history_items#destory'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
